name: Bot Diario de Noticias

on:
  schedule:
    - cron: '0 12 * * *' # 09:00 Brasília
    - cron: '0 17 * * *' # 14:00 Brasília
    - cron: '0 21 * * *' # 18:00 Brasília
  workflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Atualizar pip
        run: python -m pip install --upgrade pip

      - name: Instalar Dependências
        run: |
          pip install feedparser google-api-python-client google-auth-oauthlib google-genai pytz

      - name: Rodar Bot de Noticias
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python run_bot.py
