name: Bot Diario de Noticias

on:
  schedule:
    - cron: '0 11 * * *' # 08:00 Brasília
    - cron: '0 15 * * *' # 12:00 Brasília
    - cron: '0 21 * * *' # 18:00 Brasília
  workflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Atualizar pip
        run: python -m pip install --upgrade pip

      - name: Instalar Dependências
        run: |
          pip install feedparser
          pip install google-auth google-api-python-client google-auth-oauthlib google-auth-httplib2
          pip install google-genai

      - name: Rodar Bot de Noticias
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python run_bot.py

      - name: Salvar Log de Postagens
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add posts_publicados.txt
          git commit -m "Update logs [skip ci]" || echo "Sem mudanças para commitar"
          git push
