name: Bot Diario de Noticias

on:
  schedule:
    - cron: '0 11 * * *' # 08:00 Brasília
    - cron: '0 15 * * *' # 12:00 Brasília
    - cron: '0 21 * * *' # 18:00 Brasília
  workflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Bibliotecas Basicas
        run: pip install feedparser google-auth google-api-python-client

      - name: Rodar Bot de Noticias
        run: python run_bot.py
