name: Bots Marco Daher

on:
  schedule:
    - cron: '0 11 * * *' # Roda apenas uma vez às 08:00 AM Brasília
  workflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Bibliotecas
        run: pip install feedparser google-auth google-api-python-client google-genai

      - name: Rodar Bot de Noticias
        run: python run_bot.py

      - name: Rodar Bot de Fotografia
        run: python bot_fotografia.py
